syntax = "proto3";

package ET;

// ResponseType ObjectQueryResponse
message ObjectQueryRequest // IRequest
{
	int32 RpcId = 1;
	int64 Key = 2;
	int64 InstanceId = 3;
}

// ResponseType A2M_Reload
message M2A_Reload // IRequest
{
	int32 RpcId = 1;
}

message A2M_Reload // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType G2G_LockResponse
message G2G_LockRequest // IRequest
{
	int32 RpcId = 1;
	int64 Id = 2;
	string Address = 3;
}

message G2G_LockResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType G2G_LockReleaseResponse
message G2G_LockReleaseRequest // IRequest
{
	int32 RpcId = 1;
	int64 Id = 2;
	string Address = 3;
}

message G2G_LockReleaseResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType ObjectAddResponse
message ObjectAddRequest // IRequest
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
	ActorId ActorId = 4;
}

message ObjectAddResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType ObjectLockResponse
message ObjectLockRequest // IRequest
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
	ActorId ActorId = 4;
	int32 Time = 5;
}
message ObjectLockResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType ObjectUnLockResponse
message ObjectUnLockRequest // IRequest
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
	ActorId OldActorId = 4;
	ActorId NewActorId = 5;
}
message ObjectUnLockResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType ObjectRemoveResponse
message ObjectRemoveRequest // IRequest
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
}
message ObjectRemoveResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType ObjectGetResponse
message ObjectGetRequest // IRequest
{
	int32 RpcId = 1;
	int32 Type = 2;
	int64 Key = 3;
}
message ObjectGetResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int32 Type = 4;
	ActorId ActorId = 5;
}

// ResponseType G2R_GetLoginKey
message R2G_GetLoginKey // IRequest
{
	int32 RpcId = 1;
	string Account = 2;
}

message G2R_GetLoginKey // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Key = 4;
	int64 GateId = 5;
}

message G2M_SessionDisconnect // ILocationMessage
{
	int32 RpcId = 1;
}

message ObjectQueryResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	bytes Entity = 4;
}

// ResponseType M2M_UnitTransferResponse
message M2M_UnitTransferRequest // IRequest
{
	int32 RpcId = 1;
	ActorId OldActorId = 2;
	bytes Unit = 3;
	repeated bytes Entitys = 4;
}

message M2M_UnitTransferResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType L2G_GetRoomList
message G2L_GetRoomList // IRequest
{
	int32 RpcId = 1;
}

message L2G_GetRoomList // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	repeated int64 RoomId = 4;
	repeated int64 RoomHolderId = 5;
	repeated int32 PlayerNum = 6;
}

// ResponseType L2G_CreateRoom
message G2L_CreateRoom // IRequest
{
	int32 RpcId = 1;
	int64 PlayerId = 2;
}

message L2G_CreateRoom // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 RoomId = 4;
}

// ResponseType L2G_EnterRoom
message G2L_EnterRoom // IRequest
{
	int32 RpcId = 1;
	int64 PlayerId = 2;
	int64 RoomId = 3;
	string Name = 4;
}

message L2G_EnterRoom // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 RoomHolderId = 4;
	repeated int64 PlayerId = 5;
}

// ResponseType M2L_CreateBattleRoom
message L2M_CreateBattleRoom // IRequest
{
	int32 RpcId = 1;
	repeated int64 PlayerId = 2;
}

message M2L_CreateBattleRoom // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	ActorId ActorId = 4;
}

message L2G_NotifyStartBattle // IMessage
{
	ActorId ActorId = 1;
}

// ResponseType Room2M_Init
message M2Room_Init // IRequest
{
	int32 RpcId = 1;
	repeated int64 PlayerId = 2;
}

message Room2M_Init // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}